import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const BUILD_TYPE = process.env.BUILD_TYPE || 'LITE';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
    define: {
        'process.env.BUILD_TYPE': JSON.stringify(BUILD_TYPE),
    },
	entryPoints: ["main.ts"],
	bundle: true,
	minify: prod, 
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node", // Force Node.js platform to avoid browser-specific stream issues (like readableStream.tee)
    plugins: [
        {
            name: 'mock-pro-modules',
            setup(build) {
                if (BUILD_TYPE === 'LITE') {
                    // Mock all src/core/ (Pro modules)
                    build.onResolve({ filter: /src\/core\// }, args => {
                        return { path: args.path, namespace: 'mock-pro-modules' }
                    });
                    
                    build.onLoad({ filter: /.*/, namespace: 'mock-pro-modules' }, args => {
                        return { contents: 'module.exports = {};' }
                    });
                }
            },
        },
        {
            name: 'ignore-native-modules',
            setup(build) {
                // Ignore cpu-features (optional dependency for ssh2)
                build.onResolve({ filter: /^cpu-features$/ }, args => {
                    return { path: args.path, namespace: 'ignore-native-modules' }
                })
                
                // Ignore .node files (native bindings)
                build.onResolve({ filter: /\.node$/ }, args => {
                    return { path: args.path, namespace: 'ignore-native-modules' }
                })

                build.onLoad({ filter: /.*/, namespace: 'ignore-native-modules' }, args => {
                    return { contents: 'module.exports = {}' }
                })
            },
        },
    ],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
